"""
Injecta — Base payload provider for all DBMS
"""
from typing import Dict, List, Optional, Protocol


class PayloadProvider(Protocol):
    name: str
    comment: str
    inline_comment: str

    def version(self) -> List[str]: ...
    def databases(self) -> List[str]: ...
    def tables(self, db: str) -> List[str]: ...
    def columns(self, db: str, table: str) -> List[str]: ...
    def dump_column(self, db: str, table: str, column: str, limit: int = 0) -> List[str]: ...
    def current_user(self) -> List[str]: ...
    def current_db(self) -> List[str]: ...
    def is_admin(self) -> List[str]: ...
    def privileges(self) -> List[str]: ...
